// core/biomes.js — Biome definitions and progress mapping for Minecraft world stages.

export const BIOMES = {
  flat: {
    id: 'flat',
    name: 'Flat World',
    skyColor: 0x88c4ef,
    fogColor: 0x88c4ef,
    fogNear: 80, fogFar: 170,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xfffef8,
    sunIntensity: 1.7,
    ambientColor: 0xffffff,
    ambientIntensity: 0.35,
    hemiSky: 0xcfe8ff,
    hemiGround: 0x448a28,
    treeType: 'none',
    mountainStyle: 'flat',
  },
  hills: {
    id: 'hills',
    name: 'Home Hills',
    skyColor: 0x82bdf2,
    fogColor: 0x82bdf2,
    fogNear: 65, fogFar: 160,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xfffef8,
    sunIntensity: 1.7,
    ambientColor: 0xffffff,
    ambientIntensity: 0.35,
    hemiSky: 0xcfe8ff,
    hemiGround: 0x448a28,
    treeType: 'home_oak',
    mountainStyle: 'hills',
  },
  plains: {
    id: 'plains',
    name: 'Plains',
    skyColor: 0x7cb5ec,
    fogColor: 0x7cb5ec,
    fogNear: 60, fogFar: 140,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xfffef8,
    sunIntensity: 1.7,
    ambientColor: 0xffffff,
    ambientIntensity: 0.35,
    hemiSky: 0xcfe8ff,
    hemiGround: 0x448a28,
    treeType: 'oak',
    mountainStyle: 'hills',
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    skyColor: 0x6ca5e0,
    fogColor: 0x6ca5e0,
    fogNear: 50, fogFar: 140,
    topTexKey: 'platForestGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xfffef8,
    sunIntensity: 1.6,
    ambientColor: 0xeef6ff,
    ambientIntensity: 0.38,
    hemiSky: 0xb8e0ff,
    hemiGround: 0x245917,
    treeType: 'dense_oak',
    mountainStyle: 'forest_mountains',
  },
  desert: {
    id: 'desert',
    name: 'Desert',
    skyColor: 0xbfe0f8,
    fogColor: 0xe6d4aa,
    fogNear: 45, fogFar: 130,
    topTexKey: 'platSandTex',
    sideTexKey: 'platSandstoneTex',
    sunColor: 0xffeaaf,
    sunIntensity: 1.95,
    ambientColor: 0xfff4db,
    ambientIntensity: 0.40,
    hemiSky: 0xffe6c2,
    hemiGround: 0xa88e59,
    treeType: 'cactus',
    mountainStyle: 'mesas',
  },
  snow: {
    id: 'snow',
    name: 'Snow Tundra',
    skyColor: 0xa8cef0,
    fogColor: 0xd4e5f5,
    fogNear: 40, fogFar: 130,
    topTexKey: 'platSnowTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xebf4ff,
    sunIntensity: 1.65,
    ambientColor: 0xf0f8ff,
    ambientIntensity: 0.42,
    hemiSky: 0xe0f0ff,
    hemiGround: 0x8898a8,
    treeType: 'snow_spruce',
    mountainStyle: 'snow_peaks',
  },
  nether: {
    id: 'nether',
    name: 'The Nether',
    skyColor: 0x2b0707,
    fogColor: 0x4a0d0d,
    fogNear: 25, fogFar: 95,
    topTexKey: 'platNetherrackTex',
    sideTexKey: 'platNetherrackTex',
    sunColor: 0xff6633,
    sunIntensity: 1.4,
    ambientColor: 0x551111,
    ambientIntensity: 0.60,
    hemiSky: 0xff4422,
    hemiGround: 0x330000,
    treeType: 'nether_fungi',
    mountainStyle: 'nether_spires',
  },
  end: {
    id: 'end',
    name: 'The End',
    skyColor: 0x0b0714,
    fogColor: 0x1a0f2e,
    fogNear: 30, fogFar: 100,
    topTexKey: 'platEndstoneTex',
    sideTexKey: 'platObsidianTex',
    sunColor: 0xd8b4ff,
    sunIntensity: 1.3,
    ambientColor: 0x3d2b56,
    ambientIntensity: 0.55,
    hemiSky: 0xaa77ff,
    hemiGround: 0x180f28,
    treeType: 'end_pillar',
    mountainStyle: 'end_void',
  },
  night: {
    id: 'night',
    name: 'Moonlit Night',
    skyColor: 0x090c1b,
    fogColor: 0x0c1328,
    fogNear: 35, fogFar: 115,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0x7e9de0,
    sunIntensity: 0.65,
    ambientColor: 0x1d2645,
    ambientIntensity: 0.45,
    hemiSky: 0x223366,
    hemiGround: 0x0a1120,
    treeType: 'oak',
    mountainStyle: 'hills',
  },
  dawn: {
    id: 'dawn',
    name: 'Golden Sunrise',
    skyColor: 0xffa07a,
    fogColor: 0xffd1b3,
    fogNear: 45, fogFar: 140,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xffe0a3,
    sunIntensity: 1.8,
    ambientColor: 0xffeedb,
    ambientIntensity: 0.5,
    hemiSky: 0xffd0a8,
    hemiGround: 0x3d6628,
    treeType: 'oak',
    mountainStyle: 'hills',
  },
};

export const BIOME_ORDER = ['flat', 'hills', 'forest', 'desert', 'snow', 'nether', 'end'];

/**
 * Returns the biome object matching the given mastery progress (0.0 to 1.0).
 */
export function biomeForProgress(progress) {
  const p = Math.max(0, Math.min(1, Number.isFinite(progress) ? progress : 0));
  const idx = Math.min(BIOME_ORDER.length - 1, Math.floor(p * BIOME_ORDER.length));
  return BIOMES[BIOME_ORDER[idx]];
}
