// core/biomes.js — Biome definitions and progress mapping for Minecraft world stages.

export const BIOMES = {
  flat: {
    id: 'flat',
    name: 'Flat World',
    skyColor: 0x88c4ef,
    fogColor: 0x88c4ef,
    fogNear: 70, fogFar: 150,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xfff4e0,
    sunIntensity: 1.7,
    ambientColor: 0xffffff,
    ambientIntensity: 0.35,
    hemiSky: 0xcfe8ff,
    hemiGround: 0x6f9257,
    treeType: 'none',
  },
  plains: {
    id: 'plains',
    name: 'Plains',
    skyColor: 0x7cb5ec,
    fogColor: 0x7cb5ec,
    fogNear: 60, fogFar: 140,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xfff4e0,
    sunIntensity: 1.7,
    ambientColor: 0xffffff,
    ambientIntensity: 0.35,
    hemiSky: 0xcfe8ff,
    hemiGround: 0x6f9257,
    treeType: 'oak',
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    skyColor: 0x6ca5e0,
    fogColor: 0x6ca5e0,
    fogNear: 50, fogFar: 120,
    topTexKey: 'platGrassTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xfff0d0,
    sunIntensity: 1.6,
    ambientColor: 0xeef6ff,
    ambientIntensity: 0.38,
    hemiSky: 0xb8e0ff,
    hemiGround: 0x5a8848,
    treeType: 'dense_oak',
  },
  desert: {
    id: 'desert',
    name: 'Desert',
    skyColor: 0xbfe0f8,
    fogColor: 0xe6d4aa,
    fogNear: 45, fogFar: 120,
    topTexKey: 'platSandTex',
    sideTexKey: 'platSandstoneTex',
    sunColor: 0xffeaaf,
    sunIntensity: 1.95,
    ambientColor: 0xfff4db,
    ambientIntensity: 0.40,
    hemiSky: 0xffe6c2,
    hemiGround: 0xa88e59,
    treeType: 'cactus',
  },
  snow: {
    id: 'snow',
    name: 'Snow Tundra',
    skyColor: 0xa8cef0,
    fogColor: 0xd4e5f5,
    fogNear: 40, fogFar: 110,
    topTexKey: 'platSnowTex',
    sideTexKey: 'platDirtTex',
    sunColor: 0xebf4ff,
    sunIntensity: 1.65,
    ambientColor: 0xf0f8ff,
    ambientIntensity: 0.42,
    hemiSky: 0xe0f0ff,
    hemiGround: 0x8898a8,
    treeType: 'snow_spruce',
  },
  nether: {
    id: 'nether',
    name: 'The Nether',
    skyColor: 0x2b0707,
    fogColor: 0x4a0d0d,
    fogNear: 25, fogFar: 85,
    topTexKey: 'platNetherrackTex',
    sideTexKey: 'platNetherrackTex',
    sunColor: 0xff6633,
    sunIntensity: 1.4,
    ambientColor: 0x551111,
    ambientIntensity: 0.60,
    hemiSky: 0xff4422,
    hemiGround: 0x330000,
    treeType: 'nether_fungi',
  },
  end: {
    id: 'end',
    name: 'The End',
    skyColor: 0x0b0714,
    fogColor: 0x1a0f2e,
    fogNear: 30, fogFar: 90,
    topTexKey: 'platEndstoneTex',
    sideTexKey: 'platObsidianTex',
    sunColor: 0xd8b4ff,
    sunIntensity: 1.3,
    ambientColor: 0x3d2b56,
    ambientIntensity: 0.55,
    hemiSky: 0xaa77ff,
    hemiGround: 0x180f28,
    treeType: 'end_pillar',
  },
};

export const BIOME_ORDER = ['flat', 'plains', 'forest', 'desert', 'snow', 'nether', 'end'];

/**
 * Returns the biome object matching the given mastery progress (0.0 to 1.0).
 */
export function biomeForProgress(progress) {
  const p = Math.max(0, Math.min(1, Number.isFinite(progress) ? progress : 0));
  const idx = Math.min(BIOME_ORDER.length - 1, Math.floor(p * BIOME_ORDER.length));
  return BIOMES[BIOME_ORDER[idx]];
}
